# Generated by Django 5.1.7 on 2025-03-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf_box', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('L', 'Lost'), ('F', 'Found')], max_length=10),
        ),
    ]
