name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change if deploying from a different branch

jobs:
  deploy:
    name: Deploy to AWS Elastic Beanstalk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip Application for Deployment
        run: zip -r deploy.zip . -x "venv/*" ".git/*"

      - name: Configure AWS CLI with Temporary Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Deploy to Elastic Beanstalk
        run: |
          EB_BUCKET="elasticbeanstalk-${{ secrets.AWS_REGION }}-${{ secrets.AWS_ACCOUNT_ID }}"
          aws s3 cp deploy.zip s3://$EB_BUCKET/deploy-${{ github.run_number }}.zip
          
          aws elasticbeanstalk create-application-version --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label "ver-${{ github.run_number }}" \
            --source-bundle S3Bucket=$EB_BUCKET,S3Key=deploy-${{ github.run_number }}.zip

          aws elasticbeanstalk update-environment --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label "ver-${{ github.run_number }}"
